# Workflow that publishes the package to PyPi
name: Publish PyPi Package

# Trigger manually
on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
      - name: Install dependencies
        run: echo "Installing dependencies"
      - name: Build package
        run: echo "Building package"
      - name: Publish package
        run: echo "Publishing package"